-- =========================================================
-- めっちゃかんご：面談予約の追加
-- Supabase の SQL Editor に貼り付けて「Run」してください（何回実行しても大丈夫です）。
-- ・既存のテーブルは消しません（以前の appointments テーブルもそのまま残ります）。
-- ・新しいテーブルを足すだけです：面談の種類・状態のマスタ、面談の予約（interview_appointment）
-- ・先に add_read_status_and_symptom_info.sql を実行しておいてください（未読の点に使います）。
-- =========================================================

-- 1. マスタ（番号で管理）
create table if not exists interview_type_master (
  interview_type_id   smallint primary key,
  interview_type_name text     not null,
  sort_order          smallint not null default 0,
  delete_flag         smallint not null default 0 check (delete_flag in (0,1)),
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);
insert into interview_type_master (interview_type_id, interview_type_name, sort_order) values
  (1,'病状の説明',1),(2,'退院・転院の相談',2),(3,'リハビリ・生活の相談',3),(4,'その他',4)
on conflict (interview_type_id) do nothing;

create table if not exists interview_status_master (
  interview_status_id   smallint primary key,
  interview_status_name text     not null,
  sort_order            smallint not null default 0,
  delete_flag           smallint not null default 0 check (delete_flag in (0,1)),
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);
insert into interview_status_master (interview_status_id, interview_status_name, sort_order) values
  (1,'申込み中',1),(2,'確定',2),(3,'取り消し',3),(4,'完了',4)
on conflict (interview_status_id) do nothing;

-- 2. 面談の予約
create table if not exists interview_appointment (
  interview_id        bigint   generated by default as identity primary key,
  patient_id          bigint   not null references patient_master(patient_id),
  family_id           bigint   references family_master(family_id),       -- ご家族が申し込んだとき
  employee_id         bigint   references employee_master(employee_id),   -- 確定・変更した職員／職員が登録したとき
  interview_type_id   smallint not null references interview_type_master(interview_type_id),
  interview_status_id smallint not null default 1 references interview_status_master(interview_status_id),
  start_at            timestamptz not null,                               -- 開始日時
  duration_min        smallint not null default 30,                       -- 長さ（分）
  note                text,                                               -- ご家族・職員のひとこと
  delete_flag         smallint not null default 0 check (delete_flag in (0,1)),
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

-- 同じ時間に、有効な予約（申込み中・確定）は1件だけ（二重予約を防ぐ）
create unique index if not exists interview_one_per_start
  on interview_appointment (start_at)
  where delete_flag = 0 and interview_status_id in (1, 2);

create index if not exists interview_by_patient on interview_appointment (patient_id, start_at);

-- 3. 既読の対象に「面談」を追加（未読の点）
insert into read_target_master (target_id, target_name, sort_order) values (5,'面談予定',5)
on conflict (target_id) do nothing;

-- 4. updated_at の自動更新・アクセス権・RLS（schema.sql と同じ決まり）
do $$
declare
  t   text;
  seq text;
begin
  foreach t in array array['interview_type_master','interview_status_master','interview_appointment'] loop
    execute format('create or replace trigger %I before update on %I for each row execute function v2_set_updated_at()', t || '_updated_at', t);
    execute format('grant select, insert, update on %I to anon, authenticated', t);
    execute format('revoke delete, truncate on %I from anon, authenticated', t);
    for seq in
      select pg_get_serial_sequence(t, a.attname)
      from pg_attribute a
      where a.attrelid = t::regclass and a.attidentity <> ''
    loop
      execute format('grant usage, select on sequence %s to anon, authenticated', seq);
    end loop;
    execute format('alter table %I enable row level security', t);
    if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = t and policyname = 'v2_select') then
      execute format('create policy v2_select on %I for select to anon, authenticated using (true)', t);
    end if;
    if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = t and policyname = 'v2_insert') then
      execute format('create policy v2_insert on %I for insert to anon, authenticated with check (true)', t);
    end if;
    if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = t and policyname = 'v2_update') then
      execute format('create policy v2_update on %I for update to anon, authenticated using (true) with check (true)', t);
    end if;
  end loop;
end $$;
