-- =========================================================
-- めっちゃかんご：追加分（既読管理＋症状の説明）
-- Supabase の SQL Editor に貼り付けて「Run」してください（何回実行しても大丈夫です）。
-- ・既存のテーブルは消しません。新しいテーブルを追加して、symptom_master に 1 列足すだけです。
-- =========================================================

-- 1. 既読にする対象のマスタ（番号で管理）
create table if not exists read_target_master (
  target_id   smallint primary key,
  target_name text     not null,
  sort_order  smallint not null default 0,
  delete_flag smallint not null default 0 check (delete_flag in (0,1)),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
insert into read_target_master (target_id, target_name, sort_order) values
  (1,'AI要約',1),(2,'申し送りメモ',2),(3,'プライベートメモ',3),(4,'メッセージ',4)
on conflict (target_id) do nothing;

-- 2. 職員ごと・患者ごと・ページごとの「最後に見た日時」
create table if not exists staff_read_status (
  read_status_id bigint generated by default as identity primary key,
  employee_id    bigint   not null references employee_master(employee_id),
  patient_id     bigint   not null references patient_master(patient_id),
  target_id      smallint not null references read_target_master(target_id),
  last_read_at   timestamptz not null default now(),
  delete_flag    smallint not null default 0 check (delete_flag in (0,1)),
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  unique (employee_id, patient_id, target_id)
);

-- 最後に見た日時は、画面の時計ではなくデータベースの時刻で記録する
create or replace function v2_touch_last_read() returns trigger
language plpgsql as $$
begin
  new.last_read_at := now();
  return new;
end $$;

create or replace trigger staff_read_status_touch
  before insert or update on staff_read_status
  for each row execute function v2_touch_last_read();

-- 3. 症状マスタに「ご家族向けの説明」の列を足す
alter table symptom_master add column if not exists symptom_description text;

update symptom_master s
   set symptom_description = v.d
  from (values
    (1,'大腿骨頸部骨折','太ももの骨のつけ根（股関節に近い部分）が折れた状態です。高齢の方に多く、手術で骨を固定したり、人工の関節に置き換えたりします。そのあとはリハビリで、少しずつ立つ・歩く練習を進めます。'),
    (1,'2型糖尿病','血液中の糖（血糖）が高い状態が続く病気です。食事・運動・お薬で血糖を整えます。長く続くと目・腎臓・神経に影響が出ることがあるため、毎日の血糖の管理が大切です。'),
    (1,'虫垂炎','いわゆる「盲腸」です。大腸の入り口にある虫垂に炎症が起きた状態で、右下のお腹の痛みや発熱が出ます。お薬で治すこともあれば、手術で取ることもあります。'),
    (1,'誤嚥性肺炎','食べ物や唾液が誤って気管に入り（誤嚥）、肺に炎症が起きた状態です。抗菌薬で治療しながら、食事の形や食べる姿勢を工夫して、くり返さないようにします。'),
    (1,'脳梗塞後遺症','脳の血管が詰まる「脳梗塞」のあとに残った症状です。手足のまひ、言葉や飲み込みのしづらさなどがあり、リハビリで少しずつ回復を目指します。'),
    (2,'ペニシリン系','ペニシリン系の抗菌薬（抗生物質）で、アレルギー反応が出たことがあるという記録です。発疹などが出ることがあるため、該当するお薬は使わないようにしています。'),
    (2,'造影剤','CT などの検査で使う「造影剤」で、アレルギー反応が出たことがあるという記録です。検査の前に必ず確認し、必要なときは別の方法を選びます。'),
    (3,'高血圧','血圧が高い状態が続いていることです。血管に負担がかかるため、お薬や減塩の食事で血圧を整えます。'),
    (3,'脳梗塞','脳の血管が詰まり、その先の脳に血液が届かなくなる病気です。過去にかかったことがあるため、再発を防ぐ管理をしています。'),
    (3,'骨粗鬆症','骨の密度が下がり、骨が弱くもろくなっている状態です。転んだときなどに骨折しやすくなるため、お薬・運動・転倒の予防を行います。')
  ) as v(typ, name, d)
 where s.symptom_type_id = v.typ and s.symptom_name = v.name and s.symptom_description is null;

-- 4. updated_at の自動更新・アクセス権・RLS（schema.sql と同じ決まり）
do $$
declare
  t   text;
  seq text;
begin
  foreach t in array array['read_target_master','staff_read_status'] loop
    execute format('create or replace trigger %I before update on %I for each row execute function v2_set_updated_at()', t || '_updated_at', t);
    execute format('grant select, insert, update on %I to anon, authenticated', t);
    execute format('revoke delete, truncate on %I from anon, authenticated', t);
    for seq in
      select pg_get_serial_sequence(t, a.attname)
      from pg_attribute a
      where a.attrelid = t::regclass and a.attidentity <> ''
    loop
      execute format('grant usage, select on sequence %s to anon, authenticated', seq);
    end loop;
    execute format('alter table %I enable row level security', t);
    if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = t and policyname = 'v2_select') then
      execute format('create policy v2_select on %I for select to anon, authenticated using (true)', t);
    end if;
    if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = t and policyname = 'v2_insert') then
      execute format('create policy v2_insert on %I for insert to anon, authenticated with check (true)', t);
    end if;
    if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = t and policyname = 'v2_update') then
      execute format('create policy v2_update on %I for update to anon, authenticated using (true) with check (true)', t);
    end if;
  end loop;
end $$;
