-- =========================================================
-- めっちゃかんご v2  テーブル作成 SQL
-- 設計書：v2/docs/doa.md
--
-- ・v1 のテーブル（patients / records / chat_messages など）は読むだけで、変更しません。
--   DROP・DELETE は使っていません。ALTER は v2 の新しいテーブルにだけ使っています。
-- ・何回実行しても大丈夫です（すでにあるテーブル・データは作り直しません）。
-- ・Supabase の「SQL Editor」に全部貼り付けて「Run」で実行してください。
-- =========================================================


-- ---------------------------------------------------------
-- 0. 共通：updated_at を自動で更新する仕組み
-- ---------------------------------------------------------
create or replace function v2_set_updated_at() returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;


-- ---------------------------------------------------------
-- 1. 区分マスタ（決まった値の一覧）
-- ---------------------------------------------------------
create table if not exists sex_master (
  sex_id      smallint primary key,                 -- 0 不明 / 1 男性 / 2 女性 / 9 その他（ISO 5218）
  sex_name    text     not null,
  sort_order  smallint not null default 0,
  delete_flag smallint not null default 0 check (delete_flag in (0,1)),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create table if not exists symptom_type_master (
  symptom_type_id   smallint primary key,           -- 1 診断名 / 2 アレルギー / 3 既往歴
  symptom_type_name text     not null,
  sort_order        smallint not null default 0,
  delete_flag       smallint not null default 0 check (delete_flag in (0,1)),
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

create table if not exists condition_level_master (
  condition_level_id   smallint primary key,        -- 1 安定 / 2 要観察 / 3 要注意
  condition_level_name text     not null,
  sort_order           smallint not null default 0,
  delete_flag          smallint not null default 0 check (delete_flag in (0,1)),
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now()
);

create table if not exists memo_type_master (
  memo_type_id   smallint primary key,              -- 1 申し送り / 2 プライベート
  memo_type_name text     not null,
  sort_order     smallint not null default 0,
  delete_flag    smallint not null default 0 check (delete_flag in (0,1)),
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);


-- ---------------------------------------------------------
-- 2. 管理マスタ（管理者が増やす一覧）
-- ---------------------------------------------------------
create table if not exists role_master (
  role_id     smallint primary key,                 -- 1 医師 / 2 看護師 / ...
  role_name   text     not null,
  sort_order  smallint not null default 0,
  delete_flag smallint not null default 0 check (delete_flag in (0,1)),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create table if not exists permission_master (
  permission_id       smallint primary key,         -- 1 管理者 / 2 一般
  permission_name     text     not null,
  can_patient_create  smallint not null default 0 check (can_patient_create  in (0,1)),
  can_patient_update  smallint not null default 0 check (can_patient_update  in (0,1)),
  can_patient_delete  smallint not null default 0 check (can_patient_delete  in (0,1)),
  can_employee_manage smallint not null default 0 check (can_employee_manage in (0,1)),
  can_master_manage   smallint not null default 0 check (can_master_manage   in (0,1)),
  sort_order          smallint not null default 0,
  delete_flag         smallint not null default 0 check (delete_flag in (0,1)),
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

create table if not exists department_master (
  department_id   smallint primary key,             -- 1 内科 / 2 外科 / ...
  department_name text     not null,
  sort_order      smallint not null default 0,
  delete_flag     smallint not null default 0 check (delete_flag in (0,1)),
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create table if not exists symptom_master (
  symptom_id      integer  generated by default as identity primary key,
  symptom_type_id smallint not null references symptom_type_master(symptom_type_id),
  symptom_name    text     not null,
  sort_order      smallint not null default 0,
  delete_flag     smallint not null default 0 check (delete_flag in (0,1)),
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  unique (symptom_type_id, symptom_name)
);


-- ---------------------------------------------------------
-- 3. 人のマスタ
-- ---------------------------------------------------------
create table if not exists employee_master (
  employee_id   bigint   generated by default as identity primary key,
  employee_no   integer  not null unique,           -- 職員番号（ログイン ID）
  employee_name text     not null,
  employee_kana text,
  password_hash text     not null,                  -- SHA-256（16進数）
  role_id       smallint not null references role_master(role_id),
  permission_id smallint not null references permission_master(permission_id),
  department_id smallint references department_master(department_id),
  sort_order    smallint not null default 0,
  delete_flag   smallint not null default 0 check (delete_flag in (0,1)),
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create table if not exists patient_master (
  patient_id   bigint   generated by default as identity primary key,
  patient_no   integer  not null unique,            -- 患者番号（家族ログインの患者 ID）
  patient_name text     not null,
  patient_kana text,
  birth_date   date,
  sex_id       smallint not null default 0 references sex_master(sex_id),
  sort_order   smallint not null default 0,
  delete_flag  smallint not null default 0 check (delete_flag in (0,1)),
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create table if not exists family_master (
  family_id     bigint generated by default as identity primary key,
  patient_id    bigint not null references patient_master(patient_id),
  email         text   not null,
  password_hash text   not null,                    -- SHA-256（16進数）
  last_login_at timestamptz,
  sort_order    smallint not null default 0,
  delete_flag   smallint not null default 0 check (delete_flag in (0,1)),
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  unique (patient_id, email)
);


-- ---------------------------------------------------------
-- 4. 記録（日々増えるデータ）
-- ---------------------------------------------------------
create table if not exists admission (
  admission_id       bigint   generated by default as identity primary key,
  patient_id         bigint   not null references patient_master(patient_id),
  department_id      smallint references department_master(department_id),
  doctor_employee_id bigint   references employee_master(employee_id),   -- 主治医
  room_no            integer,
  admitted_on        date     not null,
  discharged_on      date,                                               -- 空なら入院中
  condition_level_id smallint not null default 1 references condition_level_master(condition_level_id),
  care_note          text,                                               -- 注意事項
  delete_flag        smallint not null default 0 check (delete_flag in (0,1)),
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);
-- 1 人の患者が同時に「入院中」になれるのは 1 件だけ
create unique index if not exists admission_one_open_per_patient
  on admission (patient_id) where discharged_on is null and delete_flag = 0;

create table if not exists patient_symptom (
  patient_symptom_id bigint  generated by default as identity primary key,
  patient_id         bigint  not null references patient_master(patient_id),
  symptom_id         integer not null references symptom_master(symptom_id),
  admission_id       bigint  references admission(admission_id),   -- 診断名は入院に紐付け。アレルギー・既往歴は空
  onset_on           date,                                         -- 診断日・発症日
  note               text,
  delete_flag        smallint not null default 0 check (delete_flag in (0,1)),
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

create table if not exists patient_memo (
  memo_id        bigint   generated by default as identity primary key,
  patient_id     bigint   not null references patient_master(patient_id),
  admission_id   bigint   references admission(admission_id),
  memo_type_id   smallint not null references memo_type_master(memo_type_id),
  content        text     not null,
  family_visible smallint not null default 0 check (family_visible in (0,1)),
  employee_id    bigint   references employee_master(employee_id),  -- 書いた人
  delete_flag    smallint not null default 0 check (delete_flag in (0,1)),
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create table if not exists patient_ai_summary (
  ai_summary_id  bigint generated by default as identity primary key,
  admission_id   bigint not null unique references admission(admission_id),  -- 1 入院につき 1 回だけ
  patient_id     bigint not null references patient_master(patient_id),
  generated_text text   not null,              -- AI が出した文章（変えない）
  edited_text    text,                         -- 職員が手直しした最新版
  family_visible smallint not null default 0 check (family_visible in (0,1)),
  generated_by   bigint references employee_master(employee_id),
  generated_at   timestamptz not null default now(),
  updated_by     bigint references employee_master(employee_id),
  delete_flag    smallint not null default 0 check (delete_flag in (0,1)),
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create table if not exists employee_favorite (
  employee_id bigint not null references employee_master(employee_id),
  patient_id  bigint not null references patient_master(patient_id),
  delete_flag smallint not null default 0 check (delete_flag in (0,1)),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  primary key (employee_id, patient_id)
);

create table if not exists family_chat (
  chat_id     bigint generated by default as identity primary key,
  patient_id  bigint not null references patient_master(patient_id),
  employee_id bigint references employee_master(employee_id),   -- 職員が送ったとき
  family_id   bigint references family_master(family_id),       -- 家族が送ったとき
  body        text   not null,
  read_flag   smallint not null default 0 check (read_flag in (0,1)),
  delete_flag smallint not null default 0 check (delete_flag in (0,1)),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  check ((employee_id is null) <> (family_id is null))           -- どちらか一方だけ
);

-- ※ バイタルは今は画面で使っていません（テーブルとデータは残しています）
create table if not exists vital_sign (
  vital_id     bigint generated by default as identity primary key,
  patient_id   bigint not null references patient_master(patient_id),
  admission_id bigint references admission(admission_id),
  measured_at  timestamptz not null default now(),
  body_temp    numeric(3,1),     -- 体温
  bp_systolic  smallint,         -- 血圧（上）
  bp_diastolic smallint,         -- 血圧（下）
  pulse        smallint,         -- 脈拍
  spo2         smallint,         -- 酸素飽和度
  resp_rate    smallint,         -- 呼吸数
  employee_id  bigint references employee_master(employee_id),
  delete_flag  smallint not null default 0 check (delete_flag in (0,1)),
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);


-- ---------------------------------------------------------
-- 5. updated_at の自動更新・アクセス権（v2 のテーブルだけが対象）
--    行の物理削除はしない設計なので、DELETE はできないようにします。
--    RLS（行ごとのアクセス制限）は有効にして、今は「読む・追加・更新」を全員に許可。
--    本番前にここのルールを絞れば、画面のコードを変えずに守りを固められます。
-- ---------------------------------------------------------
do $$
declare
  t   text;
  seq text;
begin
  foreach t in array array[
    'sex_master','symptom_type_master','condition_level_master','memo_type_master',
    'role_master','permission_master','department_master','symptom_master',
    'employee_master','patient_master','family_master',
    'admission','patient_symptom','patient_memo','patient_ai_summary',
    'employee_favorite','family_chat','vital_sign'
  ] loop
    -- updated_at の自動更新
    execute format('create or replace trigger %I before update on %I for each row execute function v2_set_updated_at()', t || '_updated_at', t);

    -- 権限：読む・追加・更新だけ（削除は不可）
    execute format('grant select, insert, update on %I to anon, authenticated', t);
    execute format('revoke delete, truncate on %I from anon, authenticated', t);
    for seq in
      select pg_get_serial_sequence(t, a.attname)
      from pg_attribute a
      where a.attrelid = t::regclass and a.attidentity <> ''
    loop
      execute format('grant usage, select on sequence %s to anon, authenticated', seq);
    end loop;

    -- RLS
    execute format('alter table %I enable row level security', t);
    if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = t and policyname = 'v2_select') then
      execute format('create policy v2_select on %I for select to anon, authenticated using (true)', t);
    end if;
    if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = t and policyname = 'v2_insert') then
      execute format('create policy v2_insert on %I for insert to anon, authenticated with check (true)', t);
    end if;
    if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = t and policyname = 'v2_update') then
      execute format('create policy v2_update on %I for update to anon, authenticated using (true) with check (true)', t);
    end if;
  end loop;
end $$;


-- ---------------------------------------------------------
-- 6. 初期データ：マスタ
-- ---------------------------------------------------------
insert into sex_master (sex_id, sex_name, sort_order) values
  (0,'不明',4),(1,'男性',1),(2,'女性',2),(9,'その他',3)
on conflict (sex_id) do nothing;

insert into symptom_type_master (symptom_type_id, symptom_type_name, sort_order) values
  (1,'診断名',1),(2,'アレルギー',2),(3,'既往歴',3)
on conflict (symptom_type_id) do nothing;

insert into condition_level_master (condition_level_id, condition_level_name, sort_order) values
  (1,'安定',1),(2,'要観察',2),(3,'要注意',3)
on conflict (condition_level_id) do nothing;

insert into memo_type_master (memo_type_id, memo_type_name, sort_order) values
  (1,'申し送り',1),(2,'プライベート',2)
on conflict (memo_type_id) do nothing;

insert into role_master (role_id, role_name, sort_order) values
  (1,'医師',1),(2,'看護師',2),(3,'准看護師',3),(4,'看護助手',4),
  (5,'薬剤師',5),(6,'理学療法士',6),(7,'管理栄養士',7),(8,'医療事務',8)
on conflict (role_id) do nothing;

insert into permission_master (permission_id, permission_name,
  can_patient_create, can_patient_update, can_patient_delete, can_employee_manage, can_master_manage, sort_order) values
  (1,'管理者',1,1,1,1,1,1),
  (2,'一般',  0,0,0,0,0,2)
on conflict (permission_id) do nothing;

insert into department_master (department_id, department_name, sort_order) values
  (1,'内科',1),(2,'外科',2),(3,'整形外科',3),(4,'循環器内科',4),
  (5,'呼吸器内科',5),(6,'消化器内科',6),(7,'脳神経外科',7),(8,'リハビリテーション科',8)
on conflict (department_id) do nothing;

insert into symptom_master (symptom_type_id, symptom_name) values
  (1,'大腿骨頸部骨折'),(1,'2型糖尿病'),(1,'虫垂炎'),(1,'誤嚥性肺炎'),(1,'脳梗塞後遺症'),
  (2,'ペニシリン系'),(2,'造影剤'),
  (3,'高血圧'),(3,'脳梗塞'),(3,'骨粗鬆症')
on conflict (symptom_type_id, symptom_name) do nothing;


-- ---------------------------------------------------------
-- 7. 初期データ：職員
--    パスワードはブラウザと同じ SHA-256 に変換して保存します。
--    ログイン情報の一覧は v2/README.md にあります。
-- ---------------------------------------------------------
insert into employee_master (employee_no, employee_name, employee_kana, password_hash, role_id, permission_id, department_id, sort_order) values
  (10001,'佐藤 由美',  'さとう ゆみ',     encode(sha256('admin'::bytea),'hex'), 2,1,null,1),
  (10002,'鈴木 健太',  'すずき けんた',   encode(sha256('1234'::bytea),'hex'),  2,2,5,2),
  (10003,'伊藤 さくら','いとう さくら',   encode(sha256('1234'::bytea),'hex'),  2,2,3,3),
  (20001,'渡辺 誠一',  'わたなべ せいいち',encode(sha256('1234'::bytea),'hex'), 1,2,3,4),
  (20002,'中島 恵',    'なかじま めぐみ', encode(sha256('1234'::bytea),'hex'),  1,2,5,5),
  (20003,'小川 拓也',  'おがわ たくや',   encode(sha256('1234'::bytea),'hex'),  1,2,1,6),
  (20004,'森 由香',    'もり ゆか',       encode(sha256('1234'::bytea),'hex'),  1,2,2,7)
on conflict (employee_no) do nothing;


-- ---------------------------------------------------------
-- 8. 初期データ：患者（v1 の patients と同じ 7 人。v1 側はそのまま）
-- ---------------------------------------------------------
insert into patient_master (patient_no, patient_name, patient_kana, birth_date, sex_id) values
  (100001,'田中 花子',  'たなか はなこ',   '1944-05-12',2),
  (100002,'山本 大輔',  'やまもと だいすけ','1970-02-03',1),
  (100003,'佐々木 美咲','ささき みさき',   '1992-06-21',2),
  (100004,'高橋 勇',    'たかはし いさむ', '1952-03-08',1),
  (100005,'中村 由紀子','なかむら ゆきこ', '1958-01-30',2),
  (100006,'小林 誠',    'こばやし まこと', '1981-04-17',1),
  (100007,'鈴木 幸子',  'すずき さちこ',   '1947-02-25',2)
on conflict (patient_no) do nothing;

-- 以下の記録データは、テーブルが空のときだけ入れます（何回実行しても重複しないように）
do $$
begin
  if exists (select 1 from admission) then return; end if;

  -- 入院記録
  insert into admission (patient_id, department_id, doctor_employee_id, room_no, admitted_on, condition_level_id, care_note)
  select p.patient_id, v.dept, e.employee_id, v.room, v.admitted::date, v.lvl, v.note
  from (values
    (100001,3,20001,305,'2026-07-20',2,'転倒リスク：中。夜間はナースコールの位置を確認する。'),
    (100002,1,20003,212,'2026-07-28',1,'低血糖症状に注意。'),
    (100003,2,20004,118,'2026-08-03',1,'排ガスの確認を継続。'),
    (100004,5,20002,402,'2026-08-01',3,'嚥下機能：要注意。食事は座位45度以上・見守りで実施。'),
    (100005,5,20002,210,'2026-09-23',1,'食事中のむせに注意。食後30分は上体挙上。'),
    (100006,1,20003,318,'2026-09-23',1,null),
    (100007,8,20001,115,'2026-09-23',1,'造影剤アレルギーあり。')
  ) as v(no, dept, doc, room, admitted, lvl, note)
  join patient_master  p on p.patient_no  = v.no
  join employee_master e on e.employee_no = v.doc;

  -- 患者と症状（診断名は入院に紐付け、アレルギー・既往歴は空）
  insert into patient_symptom (patient_id, symptom_id, admission_id, onset_on)
  select p.patient_id, s.symptom_id,
         case when v.typ = 1 then a.admission_id end,
         v.onset::date
  from (values
    (100001,1,'大腿骨頸部骨折','2026-07-18'),
    (100001,2,'ペニシリン系',  null),
    (100001,3,'高血圧',        null),
    (100002,1,'2型糖尿病',     '2026-07-28'),
    (100003,1,'虫垂炎',        '2026-08-02'),
    (100004,1,'誤嚥性肺炎',    '2026-08-01'),
    (100004,2,'造影剤',        null),
    (100004,3,'脳梗塞',        null),
    (100005,1,'誤嚥性肺炎',    '2026-09-23'),
    (100005,3,'骨粗鬆症',      null),
    (100006,1,'2型糖尿病',     '2026-09-23'),
    (100007,1,'脳梗塞後遺症',  '2026-09-23'),
    (100007,2,'造影剤',        null)
  ) as v(no, typ, name, onset)
  join patient_master p on p.patient_no = v.no
  join symptom_master s on s.symptom_type_id = v.typ and s.symptom_name = v.name
  join admission      a on a.patient_id = p.patient_id and a.discharged_on is null;

  -- 申し送りメモ①：v1 のカルテ・記録メモ（patients.raw_notes）をコピー
  insert into patient_memo (patient_id, admission_id, memo_type_id, content, employee_id, created_at)
  select p.patient_id, a.admission_id, 1, old.raw_notes, e.employee_id,
         (a.admitted_on + interval '3 day 9 hour') at time zone 'Asia/Tokyo'
  from (values (1,100001),(2,100002),(3,100003),(4,100004),(1790096614931,100005)) as m(v1_id, no)
  join patients        old on old.id = m.v1_id
  join patient_master  p   on p.patient_no = m.no
  join admission       a   on a.patient_id = p.patient_id and a.discharged_on is null
  join employee_master e   on e.employee_no = 10002
  where coalesce(old.raw_notes,'') <> '';

  -- 申し送りメモ②：v1 の経過データ（records の category = 'history'）を日付つきでコピー
  insert into patient_memo (patient_id, admission_id, memo_type_id, content, employee_id, created_at)
  select p.patient_id,
         case when to_date(h.j->>'date','YYYY/MM/DD') >= a.admitted_on - 7 then a.admission_id end,
         1,
         concat_ws(E'\n',
           '【' || (h.j->>'author') || '】' || (h.j->>'diag'),
           '【バイタル】' || (h.j->>'vitals'),
           '【状態】'     || (h.j->>'status'),
           '【処置】'     || (h.j->>'treat'),
           '【変化】'     || (h.j->>'change'),
           '【医師より】' || (h.j->>'doctor')),
         a.doctor_employee_id,
         (to_date(h.j->>'date','YYYY/MM/DD') + interval '10 hour') at time zone 'Asia/Tokyo'
  from (
    select r.patient_id as v1_id, r.memo::jsonb as j
    from records r where r.category = 'history'
  ) h
  join (values (1,100001),(2,100002),(3,100003),(4,100004),(1790096614931,100005)) as m(v1_id, no) on m.v1_id = h.v1_id
  join patient_master p on p.patient_no = m.no
  join admission      a on a.patient_id = p.patient_id and a.discharged_on is null;

  -- 家族に見せる申し送り・プライベートメモ（サンプル）
  insert into patient_memo (patient_id, admission_id, memo_type_id, content, family_visible, employee_id, created_at)
  select p.patient_id, a.admission_id, v.typ, v.body, v.fam, e.employee_id, v.at::timestamptz
  from (values
    (100001,1,'本日は歩行器を使って病棟を1周されました。お食事も6〜8割召し上がっています。ご家族との面会をとても楽しみにされています。',1,10003,'2026-10-07 15:00+09'),
    (100004,1,'熱は少しずつ下がってきています。食事はとろみをつけて、見守りながら召し上がっています。',1,10002,'2026-10-07 16:00+09'),
    (100005,1,'嚥下体操を毎日がんばっておられます。娘さんの面会を心待ちにされています。',1,10002,'2026-10-07 14:00+09'),
    (100001,2,'お孫さん（小学3年生）の話をすると笑顔になる。演歌が好き（美空ひばり）。朝はほうじ茶派。',0,10003,'2026-07-22 10:00+09'),
    (100002,2,'営業職。仕事復帰を気にしている。プロ野球（阪神）の話題で盛り上がる。',0,10002,'2026-07-30 11:00+09'),
    (100003,2,'保育士。「早く子どもたちに会いたい」と話す。',0,10002,'2026-08-04 10:00+09'),
    (100004,2,'元・大工。将棋が趣味。奥様を「母さん」と呼ぶ。',0,10002,'2026-08-02 10:00+09'),
    (100005,2,'編み物が趣味。手が動かせるようになったら再開したいと話す。娘さんが毎週土曜に面会。',0,10002,'2026-09-24 10:00+09')
  ) as v(no, typ, body, fam, emp, at)
  join patient_master  p on p.patient_no  = v.no
  join admission       a on a.patient_id  = p.patient_id and a.discharged_on is null
  join employee_master e on e.employee_no = v.emp;

  -- バイタル（v1 の経過データの数値を入れたもの）
  insert into vital_sign (patient_id, admission_id, measured_at, body_temp, bp_systolic, bp_diastolic, pulse, spo2, resp_rate, employee_id)
  select p.patient_id, a.admission_id, v.at::timestamptz, v.t, v.sys, v.dia, v.pr, v.sp, v.rr, e.employee_id
  from (values
    (100001,'2026-07-18 10:00+09',36.5,140,82,80,null,null),
    (100001,'2026-07-20 10:00+09',36.8,128,76,76,98,16),
    (100002,'2026-07-28 10:00+09',36.4,132,80,78,98,16),
    (100003,'2026-08-03 10:00+09',37.1,110,68,82,98,18),
    (100004,'2026-08-01 10:00+09',38.2,124,70,98,93,24),
    (100005,'2026-09-23 10:00+09',37.4,136,82,88,95,20),
    (100006,'2026-09-23 10:00+09',36.6,128,78,72,98,16),
    (100007,'2026-09-23 10:00+09',36.3,142,84,70,97,16)
  ) as v(no, at, t, sys, dia, pr, sp, rr)
  join patient_master  p on p.patient_no  = v.no
  join admission       a on a.patient_id  = p.patient_id and a.discharged_on is null
  join employee_master e on e.employee_no = 10002;

  -- 家族（ログイン情報の一覧は v2/README.md）
  insert into family_master (patient_id, email, password_hash)
  select p.patient_id, v.email, encode(sha256('1234'::bytea),'hex')
  from (values
    (100001,'tanaka.family@example.com'),
    (100004,'takahashi.family@example.com'),
    (100005,'nakamura.family@example.com')
  ) as v(no, email)
  join patient_master p on p.patient_no = v.no;

  -- チャット（サンプル）
  insert into family_chat (patient_id, family_id, body, created_at)
  select p.patient_id, f.family_id, '母の様子はいかがでしょうか。週末に面会に行く予定です。', '2026-10-06 19:00+09'
  from patient_master p join family_master f on f.patient_id = p.patient_id
  where p.patient_no = 100001;

  insert into family_chat (patient_id, employee_id, body, created_at)
  select p.patient_id, e.employee_id, 'ご連絡ありがとうございます。リハビリも順調で、面会をとても楽しみにされていますよ。', '2026-10-07 09:30+09'
  from patient_master p, employee_master e
  where p.patient_no = 100001 and e.employee_no = 10003;
end $$;
